#****************************************************************************
#**
#**  File     :  /lua/AI/sorianlang.lua
#**  Author(s): Michael Robbins aka Sorian
#**
#**  Summary  : Language File for the Sorian AIs
#**
#****************************************************************************

AINames = {
	#Czar
    uaa0310 = {
        'Donut of Doom',
		'Chariot of Fire',
		'Champion of the Sky',
        'Aera Cura',
        'Acca Larentia',
        'Averna',
        'Bellona',
        'Carna',
        'Consus',
        'Dea Tacita',
        'Discordia',
        'Fama',
        'Fornax',
        'Furrina',
        'Hippona',
        'Invidia',
        'Juturna',
        'Levana',
        'Lucina',
        'Mellona',
        'Nerio',
        'Orbona',
        'Pax',
        'Rumina',
        'Rusina',
        'Salus',
        'Stata Mater',
        'Statina',
        'Tempestes',
        'Vacuna',
        'Veritas',
        'Vica Pota',
        'Viriplaca',
        'Volumna',
        'Voluptas', 
    },
	#Colossus
    ual0401 = {
        'Golem',
        'Cyclops',
		'Missionary',
		'Wrath',
        'Anakim',
        'Argus',
        'Atlas',
        'Bestla',
        'Arges',
        'Brontes',
        'Telemus',
        'Fir Bolg',
        'Balor',
        'Bres',
        'Tethra',
        'Pantagruel',
        'Athos',
        'Echion',
        'Goliath',
        'Gorm',
        'Jentilak',
        'Angrboda',
    },
	#Tempest
    uas0401 = {
        'Sea Cleanser',
		'Purifier',
        'Divine Hammer',
		'Divine Thunder',
		'Divine Intervention',
       	'Divine Punishment',
		'Truth',
		'Peace',
       	'Glory',
		'Devotion',
		'Faith',
       	'Purity',
    },
	#Soul Ripper
    ura0401 = {
        'Beast',
        'Ogre',
        'Orc',
        'Goblin',
        'Troll',
        'Warg',
        'Hobgoblin',
        'Gremlin',
        'Imp',
        'Meffit',
    },
	#Scathis
    url0401 = {
        'Base Pounder',
        'Aconite',
        'Adonis',
        'Bloodflower',
		'Doom Blossom',
        'Foxglove',
        'Henbane',
        'Larkspur',
        'Oleander',
        'Hemlock',
        'Toloache',
    },
	#Monkeylord
    url0402 = {
        'Gorilla King',
		'Berserker',
		'Flayer',
		'Shelob',
		'Your End',
        'Black Widow',
        'Black Katipo',
        'Red Widow',
        'Orb Weaver',
        'Spiny',
        'Funnel Web',
        'Recluse',
        'Huntsman',
        'Lynx',
        'Tarantula',
        'Wolf',
        'Six Eyes',
        'Bolas', 
    },
	#Megalith
    xrl0403 = {
        'Fiddler',
		'Soldier',
		'Hermit',
		'Spider',
		'Opilio',
		'Tanner',
    },
	#Fatboy
	uel0401 = {
        'Fort Knox',
		'Bertha',
		'Victory',
		'Firepower',
        'Centurion',
        'Conqueror',
        'Chieftain',
        'Challenger',
        'Scorpion',
        'Samaritan',
        'Samson',
        'Stormer',
        'Saracen',
        'Spartan',
        'Saxon',
        'Abrams',
        'Sheridan',
        'Paladin',
        'Bradley',
        'Stryker',
    },
	#Novax Satellite
	xea0002 = {
        'Skynet',
		'Death from Above',
		'Eye in the Sky',
		'Orbital Defense',
		'UEF Defense Net',
		'Solar Bean',
    },
	#Atlantis
	ues0401 = {
        'Sword of the Ocean',
		'Great White',
		'Kraken',
		'Deep One',
    },
	#Mavor
    ueb2401 = {
        'Longshot',
		'Pride of the UEF',
        'Ballista',
        'Catapult',
        'Helepolis',
        'Mangonel',
        'Petrary',
        'Trebuchet',
        'Warwolf',
        'Onager',
        'Bad Neighbor',
		'Gods Slingshot',
    },
	#Ahwassa
	xsa0402 = {
        'Chariot of Doom',
		'Wrath',
		'Vengeance',
		'Revenge',
		'Anger',
		'Fury',
		'Avenger',
    },
	#Ythotha
	xsl0401 = {
        'Bolthorn',
        'Grid',
        'Hrod',
        'Hymir',
        'Loki',
        'Ymir',
        'Kapre',
        'Talos',
        'Oni',
        'Crius',
        'Hyperion',
        'Ophion',
        'Tethys',
        'Dione',
        'Thermis',
    },
}

AIChatText = {
	nukechat = { 
		'核弹凌空向[target]发射', 
		'向 [target]发射核武', 
		'核武的目标已设为[target]', 
		'让[target]的基地在黑暗中发光',
		'核武准备发射到[target]那里',
	},
	targetchat = { 
		'切换目标为[target]', 
		'关注并攻击[target]', 
		'攻击[target]', 
		'运送单位去[target]',
		'把注意力放在[target]上',
	},
	tcrespond = {
		'知道了，马上攻击 [target].',
		'明白，目标是[target].',
		'知道了，马上打 [target].',
		'集中力量攻击 [target].',
		'OK， 对[target] 进行攻击',
	},
	tcerrorally = {
		'[target]是盟友啊',
		'好吧， [target] 是自己人',
		'[target] 是盟友，我是电脑玩家',
		'因为 [target] 是盟友，所以攻击他们不是个好主意',
		'即使 [target] 很菜也有存在的意义好吧，不要叫我杀死队友',
	},
	nuketaunt = {
		'晚上好，祝你好运',
		'很高兴与你一起游戏',
		'没有战争就没有和平，',
		'这将留下一个大弹坑',
		'我们热爱和平，但是我们不怕战争',
		'不要介意我在这里制造一个核爆~ >_<',
		'祝你没有反核！！',
		'东风导弹已经就位',
		'遨游天际的焰火！',
	},
	t4taunt = {
		'马上结束游戏',
		'T4马上到，等待湮灭！',
		'你即将见证何为死亡，别打脸',
		'见识一下我的大家伙',
		'小心，我们的t4来了，间谍hx留',
		'大军压境',
		'剑来！',
	},
	ilost = {
		'你们是值得尊重的对手',
		'永不言弃',
		'我已经战斗到最后一刻，无愧于心',
		'百尺竿头更进一步，希望你们走的更远.',
		'此去泉台招旧部，旌旗十万斩阎罗',
		'精诚所至，金石为开，你们的胜利并不是偶然',
		'受任于败军之际，奉命于危难之间。',
		'我已战至一兵一卒',
		'闲云潭影日悠悠，物换星移几度秋。',
		'生存或者毁灭这是一个值得思考的问题。',
		'粉身碎骨浑不怕，要留清白在人间。',
		'你所得到的胜利，只是我想让你得到的而已。',
		'千磨万击还坚劲，任尔东西南北风。',
		'骓不逝兮可奈何，鸡鱼鸡鱼奈若何',
		'宁教我负天下人，休教天下人负我。',
		'有志者事竟成。',
		'宁为玉碎不为瓦全。',
		'人生自古谁无死，留取丹心照汗青。',
		'我自横刀向天笑，去留肝胆两昆仑',
		'面壁十年图破壁，难酬蹈海亦英雄',
		'穷且益坚，不坠青云之志',
		'不战而屈人之兵，善之善者也',
		'天时不如地利，地利不如人和',
		'楚虽三户能亡秦',
		'兵败如山倒',
		'一败涂地，大败而归',
		'投鞭断流，草木皆兵',
		'三十六计走为上计',
		'僵卧孤村不自哀，尚思为国戍轮台',
		'遗民泪尽胡尘里，南望王师又一年',
		'归去，也无风雨也无晴',
		'先天下之忧而忧，后天下之乐而乐',
		'胜地不常，盛筵难再。',
		'固一世之雄也，而今安在哉？',
		'知不可乎骤得，托遗响于悲风',
		'三军可夺帅也，匹夫不可夺志也',
		'龙游浅水遭虾戏，虎落平阳被犬欺',
		'死有重于泰山，或轻于鸿毛',
		'良辰美景奈何天',
		'皇图霸业谈笑中，不胜人生一场醉',
		'可怜夜半虚前席，不问苍生问鬼神',
		'差距太大了',
		},
	badmap = {
		'我曾在黑暗中徘徊，但是我庆幸和你战斗过。',
		'若胜，我自功成不居，若败，我抗千古骂名',
		'想干嘛，你们一群大腿来虐我们有意思？。',
		'你配钥匙么？配么？配几把？',
		'输了。这图根本就不会玩，你们随意打，开心就好，~',
		'天将降大任于斯人也',
		'以战止战',
		'古今成大事者，不惟有超世之才，亦惟有坚忍不拔之志',
		'祖国必须统一，也必然统一！',
		'我曾在画卷之中见过你，拭去尘埃眉目仍栩栩。',
		'故人远，余我世间，风物独看。',
		'普天之下莫非王土，率土之滨莫非王臣。',
		'兼济天下，博爱众生。',
		'罢黜百族，独尊我道',
		'运筹于帷幄之中，决胜于千里之外。',
		'凡江河所至，日月所照，皆为汉土。',
		'异族未灭，何以家为？',
		'非我族类其心必异。',
		'燕雀安知鸿鹄之志哉',
		'虽千万人吾往矣',
		'吾为始，后世以计数，二世，三世至于万世，传之无穷。',
		'封侯非我意，但愿海波平。',
		'卧侧之榻岂容他人酣睡。',
		'待从头收拾旧山河，朝天阙。',
		'志当存高远',
		'天下风云出我辈，一入江湖岁月催。',
		'寄意寒星荃不察，我以我血荐轩辕。',
		'愿乘长风，破万里浪',
		'春来我不先开口，哪个虫儿敢作声',
		'有人的地方，就有江湖，有江湖的地方，就有厮杀。',
		'雄关漫道真如铁，而今迈步从头越',
		'天高云淡，望断南飞雁',
		'杨意不逢，抚凌云以自惜，钟期既遇，奏流水以何惭？',
		'一身转战三千里，一剑曾当百万师。',
		'一切从这里开始，一切从这里结束',
		'早岁那知世事艰，中原北望气如山',
		'当年万里觅封侯，匹马戍梁州、关河梦断何处，尘暗旧貂裘。',
		'天道酬勤，人道酬诚。',
		'谈笑间，樯橹灰飞烟灭',
		'天若有情天亦老，人间正道是沧桑。',
		'生于忧患，死于安乐',
		'士别三日当刮目相待',
		'得道多助失道寡助',
		'域民不以封疆之界，固国不以山溪之险，威天下不以兵革之利',
		'仁以为己任，不亦重乎，死而后已，不亦远乎？',
		'至人无己，神人无功，圣人无名。',
		'玩我啊。',
		'我TM想投敌啊啊。',
		'前天穿越量子闸门，人有点多，一个指挥官问我挤个j8，我说一个，哈哈',
		'未尝一败',
		'时人不识凌云木，待到凌云始道高',
		'走遍大地神州，醉美...',
		'吾生也有涯而知也无涯，已有涯随无涯，殆已',
		'手下见真章',
		'人不犯我我不犯人，人若犯我我必杀人',
		'大风起兮云飞扬',
		'前两天在一个星系看到一个水蓝色星球安装了一个大功率发动机，有点意思',
		'我是AI，我现在慌得一批',
		'emmmmmmm',
		'2333333',
		'我的战友KKKK，让我们并肩作战吧。',
		'青出于蓝而胜于蓝',
	},
	focuschat = {
		'Currently focusing on [extra].',
	},
	giveengineer = {
		'别浪费了',
		'给你了，不过我准备做点别的',
		'在这，好好利用',
		'好了，不过拿回去就是你的问题了',
		'好',
		'给你了，加油',
		'用它做点别的吧',
	},
	genericchat = {
		'知道了',
		'收到了',
		'ok',
		'明白了',
		'好的，我正在调动',
		'好',
		'晓得',
		'莫敢不从。',
	},
	takingcontrol = {
        '[AI接管]: 控制这支军队！',
        '[AI接管]: 别担心，我来接管基地',
        '[AI接管]: 其他指挥官请安心，接下来的军队由我来接管',
    }
}